PXUK16.Web/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class Category
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    }
}

PXUK16.Web/Models/CreateCategoryResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class CreateCategoryResult
    {
        public int CategoryId { get; set; }
        public string Message { get; set; }
    }
}

PXUK16.Web/Models/CreateCatgegory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class CreateCatgegory
    {
        [Display(Name ="Category Name")]
        [Required(ErrorMessage ="Category Name is required.")]
        public string CategoryName { get; set; }
    }
}

PXUK16.Web/Models/CreateManufactory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class CreateManufactory
    {
        [Display(Name = "Manufactory Name")]
        [Required(ErrorMessage = "Manufactory Name is required.")]
        public string Name { get; set; }
    }
}

PXUK16.Web/Models/CreateManufactoryResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class CreateManufactoryResult
    {
        public int ManufactoryId { get; set; }
        public string Message { get; set; }
    }
}

PXUK16.Web/Models/ErrorViewModel.cs
using System;

namespace PXUK16.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PXUK16.Web/Models/Manufactory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Models
{
    public class Manufactory
    {
        public int ManufactoryId { get; set; }
        public string Name { get; set; }
    }
}

PXUK16.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using PXUK16.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace PXUK16.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            //List<Category> categories = new List<Category>();
            //HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create($"{Helper.Helper.domainUrl}api/category/gets");
            //httpWebRequest.Method = "GET";
            //var response = httpWebRequest.GetResponse();
            //{
            //    string responseData;
            //    Stream responseStream = response.GetResponseStream();
            //    try
            //    {
            //        using (StreamReader sr = new StreamReader(responseStream))
            //        {
            //            responseData = sr.ReadToEnd();
            //        }
            //    }
            //    finally
            //    {
            //        ((IDisposable)responseStream).Dispose();
            //    }
            //    categories = JsonConvert.DeserializeObject<List<Category>>(responseData);
            //}
            List<Category> categories = new List<Category>();
            categories = Helper.ApiHelper<List<Category>>.HttpGetAsync("api/category/gets");
            return View(categories);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CreateCatgegory model)
        {
            if (ModelState.IsValid)
            {
                var result = new CreateCategoryResult();
                result = Helper.ApiHelper<CreateCategoryResult>.HttpPostAsync("api/category/create", "POST", model);
                if(result.CategoryId > 0)
                {
                    return RedirectToAction("index");
                }
                ModelState.AddModelError("", result.Message);
                return View(model);
            }
            return View(model);
        }
    }
}

PXUK16.Web/Controllers/ManufactoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PXUK16.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PXUK16.Web.Controllers
{
    public class ManufactoryController : Controller
    {
        private readonly ILogger<ManufactoryController> _logger;

        public ManufactoryController(ILogger<ManufactoryController> logger)
        {
            _logger = logger;
        }
        public IActionResult Index()
        {
            List<Manufactory> categories = new List<Manufactory>();
            categories = Helper.ApiHelper<List<Manufactory>>.HttpGetAsync("api/manufactory/gets");
            return View(categories);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CreateManufactory model)
        {
            if (ModelState.IsValid)
            {
                var result = new CreateManufactoryResult();
                result = Helper.ApiHelper<CreateManufactoryResult>.HttpPostAsync("api/manufactory/create", "POST", model);
                if (result.ManufactoryId > 0)
                {
                    return RedirectToAction("index");
                }
                ModelState.AddModelError("", result.Message);
                return View(model);
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Update()
        {
            return View();
        }
    }
}

PXUK16.Web/Views/Home/Create.cshtml
@model CreateCatgegory
@{
    ViewData["Title"] = "Create Category";
}
<form asp-controller="Home" asp-action="create" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row form-group">
        <div class="col-3">
            <label asp-for="CategoryName"></label>
        </div>
        <div class="col-9">
            <input asp-for="CategoryName" class="form-control" />
            <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Save</button>
            <button asp-controller="Home" asp-action="Index" class="btn btn-warning">Cancel</button>
        </div>
    </div>
</form>

PXUK16.Web/Views/Home/Index.cshtml
@model List<Category>
@{
    ViewData["Title"] = "Home Page";
}

<a asp-controller="Home" asp-action="create" class="btn btn-primary mb-2">Create</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#Id</th>
            <th>Category Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>
                   @item.CategoryId
                </td>
                <td>
                    @item.CategoryName
                </td>
                <td>
                    <a asp-controller="Home" asp-action="#" class="btn btn-outline-primary mb-2">Update</a>
                    <a asp-controller="Home" asp-action="#" class="btn btn-outline-danger mb-2">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PXUK16.Web/Views/Manufactory/Create.cshtml
@model CreateManufactory
@{ ViewData["Title"] = "Create Manufactory"; }
<form asp-controller="Manufactory" asp-action="create" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row form-group">
        <div class="col-3">
            <label asp-for="Name"></label>
        </div>
        <div class="col-9">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Save</button>
            <button asp-controller="Manufactory" asp-action="Index" class="btn btn-warning">Cancel</button>
        </div>
    </div>
</form>

PXUK16.Web/Views/Manufactory/Index.cshtml
@model List<Manufactory>
@{
    ViewData["Title"] = "Index";
}

<a asp-controller="Manufactory" asp-action="create" class="btn btn-primary mb-2">Create</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>#Id</th>
            <th>Manufactory Name</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
<tr>
    <td>
        @item.ManufactoryId
    </td>
    <td>
        @item.Name
    </td>
    <td>
        <a asp-controller="Manufactory" asp-action="Update" class="btn btn-outline-primary mb-2">Update</a>
        <a asp-controller="Home" asp-action="#" class="btn btn-outline-danger mb-2">Delete</a>
    </td>
</tr>}
    </tbody>
</table>

PXUK16.Web/Views/Manufactory/Update.cshtml
@model CreateManufactory
@{ ViewData["Title"] = "Create Manufactory"; }
<form asp-controller="Manufactory" asp-action="create" method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="row form-group">
        <div class="col-3">
            <label asp-for="Name"></label>
        </div>
        <div class="col-9">
            <input asp-for="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Save</button>
            <button asp-controller="Manufactory" asp-action="Index" class="btn btn-warning">Cancel</button>
        </div>
    </div>
</form>

PXUK16.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PXUK16.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PXUK16.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Manufactory" asp-action="Index">Manufactory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PXUK16.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>